[project]
name = "gqr-llm-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.4",
    "gqr>=0.0.5",
    "huggingface-hub>=1.2.2",
    "matplotlib>=3.10.8",
    "ollama>=0.6.1",
]
